//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HigherManagementApis.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class snapshotCorporateIndicator
    {
        public Nullable<long> Id { get; set; }
        public int IndicatorID { get; set; }
        public string ITCProjectID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SectionID { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> FsclYear { get; set; }
        public string WBSE { get; set; }
        public System.Guid ProjectID { get; set; }
        public int LogframeNodeID { get; set; }
        public string LogFrameNodeDesc { get; set; }
        public Nullable<int> LogframeNodeOrder { get; set; }
        public Nullable<int> LogFrameNodeTypeID { get; set; }
        public string TypeOfResult { get; set; }
        public string ProjectIndicators { get; set; }
        public Nullable<decimal> Baseline { get; set; }
        public Nullable<decimal> ProjectTargets { get; set; }
        public Nullable<decimal> YearlyTargets { get; set; }
        public string MeansOfVerification { get; set; }
        public string Achievements { get; set; }
        public Nullable<int> CorporateOutcomeIndicatorID { get; set; }
        public string CorporateOutcomeIndicatorDesc { get; set; }
        public Nullable<int> CorporateOutputIndicatorID { get; set; }
        public string CorporateOutputIndicatorDesc { get; set; }
        public Nullable<int> CorporateImpactIndicatorID { get; set; }
        public string CorporateImpactIndicatorDesc { get; set; }
        public Nullable<decimal> Target_Q1 { get; set; }
        public Nullable<decimal> Target_Q2 { get; set; }
        public Nullable<decimal> Target_Q3 { get; set; }
        public Nullable<decimal> Target_Q4 { get; set; }
        public Nullable<decimal> Actual_Q1 { get; set; }
        public Nullable<decimal> Actual_Q2 { get; set; }
        public Nullable<decimal> Actual_Q3 { get; set; }
        public Nullable<decimal> Actual_Q4 { get; set; }
        public Nullable<decimal> TargetPTD { get; set; }
        public Nullable<decimal> ActualPTD { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
    }
}
